apiVersion: extensions/v1
kind: Deployment
metadata:
  name: api-vol
spec: 
  replicas: 1 
  template:
    metadata:
      labels:
        app: api-vol
    spec:
      containers:
      - name: api-vol
        image: richardruiz/prueba
        ports:
        - containerPort: 80
        resources:
            requests:
              cpu: "7"
            limits: 
              cpu: "8"
---
apiVersion: v1
kind: Service
metadata:
 name: api-vol
spec:
 type: LoadBalancer
 selector:
   app: api-vol
 ports:
   - name: client
     protocol: TCP
     port: 80
     nodePort: 32080
 selector:
   app: api-vol