apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api-back
spec: 
  replicas: 1 
  template:
    metadata:
      labels:
        app: api-back
    spec:
      containers:
      - name: api-back
        image: cuestionarios.azurecr.io/api
        ports:
        - containerPort: 80
        resources:
            requests:
              cpu: "7"
            limits: 
              cpu: "8"
      imagePullSecrets:
      - name: api-cuestionarios
---
apiVersion: v1
kind: Service
metadata:
 name: api-back
spec:
 type: LoadBalancer
 selector:
   app: api-back
 ports:
   - name: client
     protocol: TCP
     port: 80
     nodePort: 32084
 selector:
   app: api-back