apiVersion: v1
kind: Service
metadata:
  name: my-api-back-svc
  labels:
    app: api-back
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: api-back
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-api-back
  labels:
    app: api-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-back
  template:
    metadata:
      labels:
        app: api-back
    spec:
      containers:
      - name: api-back
        image: cuestionarios.azurecr.io/apipruebas
        ports:
        - containerPort: 80
        resources:
            requests:
              cpu: "7"
            limits: 
              cpu: "8"
      imagePullSecrets:
      - name: api-cuestionarios
